# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/resources/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# base import
import os
# 3-rd party libs
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    @staticmethod
    def get_absolute_path_to_image(image_name: str = '') -> str:
        return f'{os.path.dirname(__file__)}/resources/images/{image_name}'

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 315)
        MainWindow.setMinimumSize(QtCore.QSize(650, 315))
        MainWindow.setMaximumSize(QtCore.QSize(650, 315))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.get_absolute_path_to_image('document-speech.png')), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(109543, 109543))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 5, 640, 305))
        self.tabWidget.setMinimumSize(QtCore.QSize(640, 305))
        self.tabWidget.setMaximumSize(QtCore.QSize(640, 305))
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setObjectName("tabWidget")
        self.document_tab = QtWidgets.QWidget()
        self.document_tab.setObjectName("document_tab")
        self.btnChooseFile = QtWidgets.QPushButton(self.document_tab)
        self.btnChooseFile.setGeometry(QtCore.QRect(5, 10, 625, 36))
        self.btnChooseFile.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnChooseFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnChooseFile.setObjectName("btnChooseFile")
        self.widget = QtWidgets.QWidget(self.document_tab)
        self.widget.setGeometry(QtCore.QRect(10, 50, 611, 47))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 45))
        self.label.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbSpeechLanguage_1 = QtWidgets.QComboBox(self.widget)
        self.cmbSpeechLanguage_1.setMinimumSize(QtCore.QSize(75, 32))
        self.cmbSpeechLanguage_1.setMaximumSize(QtCore.QSize(75, 32))
        self.cmbSpeechLanguage_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbSpeechLanguage_1.setAcceptDrops(False)
        self.cmbSpeechLanguage_1.setMaxCount(7151)
        self.cmbSpeechLanguage_1.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cmbSpeechLanguage_1.setIconSize(QtCore.QSize(8, 8))
        self.cmbSpeechLanguage_1.setObjectName("cmbSpeechLanguage_1")
        self.cmbSpeechLanguage_1.addItem("")
        self.cmbSpeechLanguage_1.addItem("")
        self.horizontalLayout.addWidget(self.cmbSpeechLanguage_1)
        self.btnChooseFolder = QtWidgets.QPushButton(self.document_tab)
        self.btnChooseFolder.setGeometry(QtCore.QRect(5, 120, 625, 36))
        self.btnChooseFolder.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnChooseFolder.setObjectName("btnChooseFolder")
        self.btnPerform = QtWidgets.QPushButton(self.document_tab)
        self.btnPerform.setGeometry(QtCore.QRect(5, 225, 625, 36))
        self.btnPerform.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPerform.setAutoFillBackground(False)
        self.btnPerform.setStyleSheet("QPushButton { background-color: rgb(0, 80, 144); color: white; }")  # rgb(48,140,198)
        self.btnPerform.setObjectName("btnPerform")
        self.tabWidget.addTab(self.document_tab, icon, "")
        self.live_tab = QtWidgets.QWidget()
        self.live_tab.setObjectName("live_tab")
        self.tbLive = QtWidgets.QTextEdit(self.live_tab)
        self.tbLive.setGeometry(QtCore.QRect(5, 5, 625, 200))
        self.tbLive.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbLive.setToolTipDuration(5)
        self.tbLive.setObjectName("tbLive")
        self.cmbSpeechLanguage_2 = QtWidgets.QComboBox(self.live_tab)
        self.cmbSpeechLanguage_2.setGeometry(QtCore.QRect(520, 230, 75, 32))
        self.cmbSpeechLanguage_2.setMinimumSize(QtCore.QSize(75, 32))
        self.cmbSpeechLanguage_2.setMaximumSize(QtCore.QSize(75, 32))
        self.cmbSpeechLanguage_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmbSpeechLanguage_2.setAcceptDrops(False)
        self.cmbSpeechLanguage_2.setMaxCount(7151)
        self.cmbSpeechLanguage_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cmbSpeechLanguage_2.setIconSize(QtCore.QSize(8, 8))
        self.cmbSpeechLanguage_2.setObjectName("cmbSpeechLanguage_2")
        self.cmbSpeechLanguage_2.addItem("")
        self.cmbSpeechLanguage_2.addItem("")
        self.btnMuteUnmute = QtWidgets.QPushButton(self.live_tab)
        self.btnMuteUnmute.setGeometry(QtCore.QRect(600, 230, 32, 32))
        self.btnMuteUnmute.setMinimumSize(QtCore.QSize(32, 32))
        self.btnMuteUnmute.setMaximumSize(QtCore.QSize(32, 32))
        self.btnMuteUnmute.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnMuteUnmute.setToolTipDuration(5)
        self.btnMuteUnmute.setText("")
        # region Icons
        self.ICON_UNMUTED = QtGui.QIcon()
        self.ICON_UNMUTED.addPixmap(QtGui.QPixmap(self.get_absolute_path_to_image("unmuted.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ICON_MUTED = QtGui.QIcon()
        self.ICON_MUTED.addPixmap(QtGui.QPixmap(self.get_absolute_path_to_image("muted.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # endregion
        self.btnMuteUnmute.setIcon(self.ICON_UNMUTED)
        self.btnMuteUnmute.setIconSize(QtCore.QSize(16, 16))
        self.btnMuteUnmute.setCheckable(True)
        self.btnMuteUnmute.setChecked(True)
        self.btnMuteUnmute.setFlat(False)
        self.btnMuteUnmute.setObjectName("btnMuteUnmute")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.get_absolute_path_to_image("live-speech.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.live_tab, icon2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cmbSpeechLanguage_1.setCurrentIndex(0)
        self.cmbSpeechLanguage_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LettersVoice"))
        self.btnChooseFile.setText(_translate("MainWindow", "Choose file ..."))
        self.label.setText(_translate("MainWindow", "Choose the document language"))
        self.cmbSpeechLanguage_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select language for live speeching</p></body></html>"))
        self.cmbSpeechLanguage_1.setCurrentText(_translate("MainWindow", "en"))
        self.cmbSpeechLanguage_1.setItemText(0, _translate("MainWindow", "en"))
        self.cmbSpeechLanguage_1.setItemText(1, _translate("MainWindow", "ru"))
        self.btnChooseFolder.setText(_translate("MainWindow", "Choose folder to save speech file ..."))
        self.btnPerform.setText(_translate("MainWindow", "Perform file speeching"))
        self.tbLive.setToolTip(_translate("MainWindow", "<html><head/><body><p>Live speeching while typing</p></body></html>"))
        self.cmbSpeechLanguage_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select language for live speeching</p></body></html>"))
        self.cmbSpeechLanguage_2.setCurrentText(_translate("MainWindow", "en"))
        self.cmbSpeechLanguage_2.setItemText(0, _translate("MainWindow", "en"))
        self.cmbSpeechLanguage_2.setItemText(1, _translate("MainWindow", "ru"))
        self.btnMuteUnmute.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mute/Unmute</p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
